about/urls.py
from django.urls import path
from . import views

urlpatterns = [

    path('', views.index),

]

career/urls.py
from django.urls import path
from django.conf.urls import url
from . import views


app_name = 'career'

urlpatterns = [


    path('', views.index),
    url(r'^(?P<slug>[\w-]+)/$', views.vacancy_details, name='details')


]

contact/urls.py
from django.urls import path
from . import views

urlpatterns = [

    path('', views.index),

]

django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('home/', include('home.urls')),
    path('career/', include('career.urls')),
    path('contact/', include('contact.urls')),
    path('about/', include('about.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

urlpatterns = [

    path('', views.index),
    path('home/', views.index),



]

about/models.py
from django.db import models


class TeamMember(models.Model):
    name = models.CharField(max_length=50)
    profile_pic = models.ImageField(default='default.png', blank=True)
    title = models.CharField(max_length=50)
    linkedin = models.URLField(max_length=200, blank=True)
    facebook = models.URLField(max_length=200, blank=True)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):  # return name of team member while querying
        return self.name


class PhotoGallery(models.Model):
    photo = models.ImageField()
    title = models.CharField(default='myphoto', max_length=50)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

career/models.py
from django.db import models


class Vacancy(models.Model):
    title = models.CharField(max_length=50)
    JOB = 'Job'
    INTERN = 'Intern'
    VACANCY_TYPE_CHOICES = (
        (JOB, 'Job'),
        (INTERN, 'Intern'),
    )
    type = models.CharField(
        max_length=10,
        choices=VACANCY_TYPE_CHOICES,
        default=JOB,
    )
    slug = models.CharField(max_length=50, default=title)
    summary = models.TextField()
    responsibilities = models.TextField()
    requirements = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    def snip(self):
        return self.summary[:40]+'...'

    def monthname(self):
        n = int(self.date.month)
        months = (
            'Jan',
            'Feb',
            'Mar',
            'Apr',
            'May',
            'Jun',
            'Jul',
            'Aug',
            'Sep',
            'Oct',
            'Nov',
            'Dec'
        )
        return months[n-1]

contact/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models

# Create your models here.

about/views.py
from django.shortcuts import render
from .models import TeamMember
from .models import PhotoGallery


def index(request):
    team_members = TeamMember.objects.all().order_by('date')
    photo_gallery = PhotoGallery.objects.all()
    return render(request, '../templates/about/about_index.html', {'team_members': team_members, 'photo_gallery': photo_gallery})

career/views.py
from django.shortcuts import render
from .models import Vacancy


def index(request):

    vacancies = Vacancy.objects.all().order_by('date')
    return render(request, '../templates/career/career_index.html', {'vacancies': vacancies})


def vacancy_details(request, slug):
    vacancy = Vacancy.objects.get(slug=slug)
    return render(request, '../templates/career/vacancy_details.html', {'vacancy': vacancy})

contact/views.py
from django.shortcuts import render


def index(request):
    return render(request, '../templates/contact/contact_index.html')

home/views.py
from django.shortcuts import render


def index(request):
    return render(request, '../templates/home/home_index.html')

about/templates/about/about_index.html
{% extends 'main_layout.html' %}

{% block content %}

{% load static from staticfiles %}
    <link rel="stylesheet" href="{% static 'about_assets/about_style.css' %}">
    <br><br><br>
<div class="photo-gallery">
    <section id="slider" class="containers">
		<ul class="slider-wrapper">
            {% for photos in photo_gallery %}
		<li class="current-slide">
            <img src="{{ photos.photo.url }}" alt = "photo"></li>
            {% endfor %}
        </ul>
        <div class="slider-shadow"></div>


		<ul id="control-buttons" class="control-buttons"></ul>
    </section>
<script src='https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js'></script>
            <script  src="{%static 'about_assets/js/index.js' %}"></script>
</div>
 <a class="contacts__link" style="margin-left: 50px"><img src="{% static 'icons/logo_main_small.png' %}">
              <h1 class="contacts_title-ag">Bit4stack<span class="contacts--light">.com</span></h1></a>
<div class="sect sect--padding-bottom">
<h1 class="desc">Bit4Stack is a tech company. Company focuses on the leading trend of online learning.
With the well skilled team members we provide various tech
services: Mobile apps development, Web apps, ML algorithm analysis,IoT & AI projects and many more.
The company does various researches in the field of IoT,AI,Big Data.

</h1>
<h1 class="title"><strong>Board of Directors</strong></h1>
</div>
    <div class="card-wrapper" >

{% for team_member in team_members  %}
        <div class="card">

          <div class="card-image">
            <img src="{{ team_member.profile_pic.url }}" alt="profile_pic">
          </div>
            <div class="details">
          <h3>{{ team_member.name }}
            <br>
            <span class="job-title">{{ team_member.title }}</span>
              <br>
                <a href="{{ team_member.linkedin }}">
                    <img src="{% static 'icons/linkedin.png' %}"> </a>
                    <a href="{{ team_member.facebook }}">
              <img src="{% static 'icons/facebook.png' %}">
            </a>

          </h3>
        </div>
      </div>

{% endfor %}
<br>
    <br>
    <br>
    </div>




        <style media="screen">

            .card-wrapper {
                margin-top: auto;
                width: 100%;
                height: auto;
                text-align: center;
            }

            .card {

                position: relative;
                display: inline-block;
                overflow: hidden;
                margin: 20px 0px 20px 50px;
                width: 250px;
                height: 350px;
                border-radius: 16px;
                box-shadow: 0 5px 18px rgba(0, 0, 0, 0.6);
                transition: 0.5s;
                text-align: center;

                .card-image {
                     position: absolute;
                     top: 0px;
                     left: 0px;
                     width: 100%;
                     height: 100%;
                     z-index: 2;
                     background-color: #000;
                     transition: .5s;
                }

                &:hover img {
                opacity: 0.4;
                transition: .5s;
                }
            }

            .card:hover .card-image {
              transform: translateY(-100px);
              transition: all .9s;
            }

            /**** Social Icons *****/

            .social-icons {
              position: absolute;
              top: 65%;
              left: 70%;
              transform: translate(-50%, -50%);
              z-index: 3;
              display: flex;


            }

            .card:hover .social-icons li a {
              transform: translateY(0px);
              opacity: 1;
            }

            .social-icons li a:hover {
              background: #000;
              transition: .2s;
            }
            .details {
                position: absolute;
                bottom: 0;
                left: 0;
                background: lavender;
                width: 100%;

                z-index: 1;
                padding: 10px;

              h3 {
                padding: 10px;
                alignment: center;

                .job-title {
                    font-size: 1rem;
                    line-height: 2.5rem;
                    color: #333;
                    font-weight: 300;
                }
              }
            }

        </style>



{% endblock %}

career/templates/career/career_index.html
 {% extends 'main_layout.html' %}
 {% block content %}

 {% load static from staticfiles %}

     <div class="site">
     <img class="site__imgs" src="{% static 'career_assets/career-banne.jpg' %}">
         <br>
         <br>
         <h1 class="site__subtitle">Working with us is a great opportunity to enhance the skills and improve quality.
             <br>
         With great team support and resources one can feel great joy at work.

              Bit4stack offers a wide range of work opportunities for fresh graduates where you start with real and meaningful projects from day one. We are an innovative company where we value raw ideas and thinking. You will get to work with experienced colleagues who will help you learn and enhance your skills.

We are looking for individuals who are motivated to learn and develop. This is the right place to start if you are looking for interesting and challenging assignments, and if you want to bring new ideas to our business. Some examples of entry-level roles include: Engineer, Designer, Developer,Marketing Assistant and many more.
         </h1>
     </div>
<div class="sect sect--white">
<div class="container">
  <div class="row">
   <h1 class="row__title">
    What we expect from Bit4stack?
  </h1>
  <h2 class="row__sub"></h2>
  </div>

  <div class="row row--margin">
    <div class="col-md-6 article-pre__col">

        <a class="contacts__link"><img src="{% static 'career_assets/teamwork.png' %}"></a>
        <h1 class="row__title">Team Work</h1>
    </div>
      <div class="col-md-6 article-pre__col">
          <a class="contacts__link"><img src="{% static 'career_assets/learn.png' %}"></a>
          <h1 class="row__title">Always be learning</h1></a>
    </div>
 </div>
  <div class="row">
     <div class="col-md-6 article-pre__col">
         <a class="contacts__link"><img src="{% static 'career_assets/explore.png' %}"></a>
         <h1 class="row__title">Opportunity to explore</h1>
    </div>
      <div class="col-md-6 article-pre__col">
          <a class="contacts__link"><img src="{% static 'career_assets/Opportunity.png' %}"></a>
          <h1 class="row__title">Endless opportunities</h1>
    </div>
  </div>
</div>
</div>

 <h1 class="row__title" style="background-color: #815ba7">
     Vacancy Lists</h1>
<link rel='stylesheet' href='{% static 'career_assets/styles.css' %}'>
 <div class="row">

 {% for vacancy in vacancies %}
  <div class="example-1 card">

    <div class="wrapper">
      <div class="date">
        <span class="day">{{ vacancy.date.day }}</span>
        <span class="month">{{ vacancy.monthname }}</span>
        <span class="year">{{ vacancy.date.year }}</span>
      </div>
      <div class="data">
        <div class="content">
            <span class="author">Type: {{ vacancy.type }}</span>
            <h1 class="vacancy_title">{{ vacancy.title }}</h1>
            <a class="btn btn--revert btn--width" style="margin-left: 80px" href="{% url 'career:details' slug=vacancy.slug %}">Details</a>

        </div>

      </div>
    </div>
  </div>

{% endfor %}
</div>


<br>
     <br>
     <br>



 {% endblock %}

career/templates/career/vacancy_details.html
{% extends 'main_layout.html' %}

{% block content %}

{% load static from staticfiles %}

    <h1>hello</h1>

    <h1>{{ vacancy.title }}</h1>
    <h1>{{ vacancy.type }}</h1>
    <h1>{{ vacancy.summary }}</h1>
    <h1>{{ vacancy.resposibilities }}</h1>
    <h1>{{ vacancy.requirements }}</h1>


{% endblock %}

contact/templates/contact/contact_index.html
{% extends 'main_layout.html' %}

{% block content %}

{% load static from staticfiles %}



    <div class="sect sect--padding-bottom">
  <div class="container">
    <div class="row">
     <h1 class="row__title">
    Contact Us </h1>
  <h2 class="row__sub">Feel free to ask any questions</h2>
    </div>
    <div class="row row--margin">
      <div class="col-md-1"></div>
      <div class="col-md-4">
        <div class="contacts">
          <a class="contacts__link"><img src="{% static 'icons/logo_main_small.png' %}">
              <h1 class="contacts_title-ag">Bit4stack<span class="contacts--light">.com</span></h1></a>
          <p class="contacts__address">
           Buddhanagar<br>
            New Baneshwor<br>
           Kathmandu, Nepal
          </p>
          <p class="contacts__info">
            tel. <a  class="contacts__info-link">+9779843222111</a>
          </p>
          <p class="contacts__info">
            m. <a href="#"class="contacts__info-link">info@bit4stack</a>
          </p>
        </div>
      </div>
      <div class="col-md-6">
        <form id="contact" class="form">

           <div class="form-group">
             <div class="form__field--half">
            <input type="text" placeholder="Name*" class="form__field form__text">
             </div>
          <div class="form__field--half">
          <input type="text" placeholder="Surname" class="form__field form__text">
          </div>
          </div>

        <div class="form-group">
          <div class="form__field--half">
            <input type="text" placeholder="Email address*" class="form__field form__text">
          </div>
         <div class="form__field--half">
          <input type="text" placeholder="Phone number" class="form__field form__text">
    </div>
          </div>

          <div class="form-group">
            <textarea type="text" placeholder="Your messsage*" class="form__field form__textarea"></textarea>
            <button class="btn btn--up btn--width" type="submit">Submit</button>
          </div>
        </form>
      </div>
<div class="col-md-1"></div>
    </div>
  </div>
</div>
<div class="map-view">
   <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1766.4221894734878!2d85.33357323173604!3d27.691204316154856!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x61931102f3dec369!2sCambridge+Boys+Hotel!5e0!3m2!1sen!2snp!4v1544275200826"
           width="600" height="150" frameborder="0" style="border:0" allowfullscreen></iframe>
</div>
{% endblock %}

home/templates/home/home_index.html
{% extends 'main_layout.html' %}


{% block content %}
{% load static from staticfiles %}


<div class="slideshow">
    <main class="main-content">
  <section class="slideshow">
    <div class="slideshow-inner">
      <div class="slides">
        <div class="slide is-active ">
          <div class="slide-content">
            <div class="caption">
              <div class="title">Online Learning</div>
              <div class="text">
                <p>Online course videos</p>
              </div>
              <a href="#" class="slideshow_btn">
                <span class="btn-inner">Learn More</span>
              </a>
            </div>
          </div>
          <div class="image-container">
            <img src="http://www.hrea.org/wp-content/uploads/2014/11/placeholder-blog-image.jpg" alt="" class="image" />
          </div>
        </div>
        <div class="slide">
          <div class="slide-content">
            <div class="caption">
              <div class="title">Internet of Things, AI</div>
              <div class="text">
                <p>Connected Devices,Reinforcement Learning, NLP & Predictive API</p>
              </div>
              <a href="#" class="slideshow_btn">
                <span class="btn-inner">Learn More</span>
              </a>
            </div>
          </div>
          <div class="image-container">
            <img src=" https://wallpapercave.com/wp/wp2042044.jpg" alt="" class="image" />
          </div>
        </div>
        <div class="slide">
          <div class="slide-content">
            <div class="caption">
              <div class="title">Web Development</div>
              <div class="text">
                <p>MEAN Stack, PHP, Java, Python + Django + flask</p>
              </div>
              <a href="#" class="slideshow_btn">
                <span class="btn-inner">Learn More</span>
              </a>
            </div>
          </div>
          <div class="image-container">
            <img src=" http://hdqwalls.com/wallpapers/web-development-minimalism-bl.jpg" alt="" class="image" />
          </div>
        </div>
        <div class="slide">
          <div class="slide-content">
            <div class="caption">
              <div class="title">App Development</div>
              <div class="text">
                <p>Java + Kotlin + Swift </p>
              </div>
              <a href="#" class="slideshow_btn">
                <span class="btn-inner">Learn More</span>
              </a>
            </div>
          </div>
          <div class="image-container">
            <img src=" https://i.pinimg.com/originals/1e/10/a3/1e10a321dd472b15f2abfb99e1b18951.jpg" alt="" class="image" />
          </div>
        </div>
      </div>
      <div class="pagination">
        <div class="item is-active">
          <span class="icon">1</span>
        </div>
        <div class="item">
          <span class="icon">2</span>
        </div>
        <div class="item">
          <span class="icon">3</span>
        </div>
        <div class="item">
          <span class="icon">4</span>
        </div>
      </div>

    </div>
  </section>
</main>
  <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js'></script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/gsap/1.19.1/TweenMax.min.js'></script>
    <script  src="{% static 'home_assets/slideshow/js/index.js' %}"></script>
</div>
<div class="sect sect--padding-top">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
    <div class="site">
        <br>

      <h1 class="site__title">Welcome!!!</h1>
               <br>
         <a class="contacts__link" style="margin-left: 50px"><img src="{% static 'icons/logo_main_small.png' %}">
              <h1 class="contacts_title-ag">Bit4stack<span class="contacts--light">.com</span></h1></a>
        <h2 class="site__subtitle">We Provide What you need</h2>
      <div class="site__box-link">

        <a class="btn btn--revert btn--width" href="/contact">Contact</a>
      </div>
      <img class="site__img" src="https://image.ibb.co/c7grYb/image3015.png">
    </div>
    </div>
    </div>
  </div>
</div>
 <div class="sect sect--padding-bottom">
<div class="container">
<div class="row row--center">
  <h1 class="row__title">
    Our Services
  </h1>
  <h2 class="row__sub">"Get the best support from us"</h2>
</div>
<div class="row row--center row--margin">
  <div class="col-md-4 col-sm-4 price-box price-box--purple">
    <div class="price-box__wrap">
      <div class="price-box__img"></div>
      <h1 class="price-box__title">
        Online Courses
      </h1>
      <p class="price-box__people">

      </p>

      </h3>
      <p class="price-box__feat">
        Course Lists
      </p>
      <ul class="price-box__list">
        <li class="price-box__list-el">GMAT</li>
        <li class="price-box__list-el">GRE,TOEFL</li>
        <li class="price-box__list-el">EPS Exam</li>
        <li class="price-box__list-el">Python,Java</li>
        <li class="price-box__list-el">Game Development</li>
        <li class="price-box__list-el">Android </li>
        <li class="price-box__list-el">PHP, .Net</li>
      </ul>
       <div class="price-box__btn">
      <a class="btn btn--purple btn--width"></a>
    </div>
  </div>
  </div>
  <!-- second -->
  <div class="col-md-4 col-sm-4 price-box price-box--violet">
  <div class="price-box__wrap">
      <div class="price-box__img"></div>
      <h1 class="price-box__title">
        IoT,Machine Learning,AI
      </h1>
      <p class="price-box__people">
        Various Company Projects
      </p>

      <p class="price-box__feat">
        Project Lists
      </p>
      <ul class="price-box__list">
        <li class="price-box__list-el">Vehicle Monitoring System</li>
        <li class="price-box__list-el">Auto responder of Emails</li>
        <li class="price-box__list-el">Advanced Password Generator</li>
        <li class="price-box__list-el">Automation of Tic-Tac-Toe</li>
        <li class="price-box__list-el">Data Analyzer </li>
      </ul>
      <div class="price-box__btn">
      <a class="btn btn--violet btn--width"></a>
    </div>
  </div>
  </div>

<!-- third -->
  <div class="col-md-4 col-sm-4 price-box price-box--blue">
  <div class="price-box__wrap">
      <div class="price-box__img"></div>
      <h1 class="price-box__title">
        Apps & Web Development
      </h1>
      <p class="price-box__people">
        Worked over many projects
      </p>

      <p class="price-box__feat">
        Service Lists
      </p>
      <ul class="price-box__list">
        <li class="price-box__list-el">Android App</li>
        <li class="price-box__list-el">Web Hosting & Support</li>
        <li class="price-box__list-el">Web Development & Security:PHP,Java Script</li>
        <li class="price-box__list-el">Web Apps:Django,Java</li>

      </ul>
    <div class="price-box__btn">
      <a class="btn btn--blue btn--width"></a>
    </div>
  </div>
  </div>
</div>
</div>
 </div>





<div class="site">
<h1 class="site__title">How we handle projects?</h1>
      <img class="site__imgs" src="{% static 'home_assets/planning.png' %}">

</div>
    <div class="map-view">
   <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1766.4221894734878!2d85.33357323173604!3d27.691204316154856!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x61931102f3dec369!2sCambridge+Boys+Hotel!5e0!3m2!1sen!2snp!4v1544275200826"
           width="600" height="150" frameborder="0" style="border:0" allowfullscreen></iframe>
</div>




{% endblock %}

templates/main_layout.html
{% block content_main %}
{% load static from staticfiles %}
 <!DOCTYPE html>
<html lang="en" >

<head>
  <meta charset="UTF-8">
  <title>Bit4stack</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'icons/logo_main_small.png' %}">
    <link rel='stylesheet' href='{% static 'bootstrap-3.3.7/css/bootstrap.min.css' %}'>
    <link rel="stylesheet" href="{% static 'styles/style.css' %}">
</head>

<body>

  <head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
 <meta name="theme-color" content="#1885ed">
  <title>Homepage</title>
</head>


<div class="header__menu">
    <nav id="navbar" class="navbar-fixed-top">
      <ul class="header__elenco">
         <li class="header__el header__el--blue"><a href="/home" class="btn btn--width"><strong>Home →</strong></a></li>
         <li class="header__el header__el--blue"><a href="/career" class="btn btn--width"><strong>Career →</strong></a></li>
         <li class="header__el header__el--blue"><a href="/contact" class="btn btn--width"><strong>Contact →</strong></a></li>
         <li class="header__el header__el--blue"><a href="/about" class="btn btn--width"><strong>About →</strong></a></li>
      </ul>
    </nav>
  </div>
    </div>

<div class="sect sect--padding-top">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
    <div class="site">


      </div>

    </div>
    </div>
    </div>
  </div>
</div>
<div class="content related-widget-wrapper">
{% block content %}

{% endblock %}

</div>

   <div class="sect sect--violet ">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h1 class="career_title">Oh! Your have digged our website in search for any services or query?</h1>
        <h1 class="career_sub">We will pleased to have you.</h1>
        <a href="/contact" class="btn btn--width">Contact</a>
      </div>
    </div>
  </div>

</div>

<footer class="footer">
  <div class="container">
    <div class="row">
      <div class="col-md-2 col-xs-6">

       <img class="footer__img" src="{% static 'icons/logo_main_small.png' %}">
          <h1 class="footer__title">Bit4stack<span class="footer__light">.com</span></h1></div>
        <div class="footer__social">
              <h2 class="career_title">Navigation</h2>
          <ul>
                        <li><a href="/home" class="career_sub">Home</a></li>
                        <li><a href="/career" class="career_sub">Career</a></li>
                        <li><a href="/contact" class="career_sub">Contact</a></li>
                        <li><a href="/about" class="career_sub">About</a></li>
                    </ul>
        </div>
      <div class="col-md-10 col-xs-6">
          <div class="footer__social">

          <a href="#" class="footer__social-l">
            <img src=" {% static 'icons/linkedin.png' %}">       </a>
          <a href="#" class="footer__social-l">
            <img src=" {% static 'icons/facebook.png' %}">         </a>
        </div>
      </div>

<div class="footer_description">Copyright@Bit4stack Inc. || All right reserved</div>
    </div>

  </div>
</footer>

<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js'></script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js'></script>
</body>
</html>

{% endblock %}